// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAouyOtMvueIizn4ETJMTtH5RdmkprKdHw',
    appId: '1:560383687339:web:38b58cb8520eada3d1d5ee',
    messagingSenderId: '560383687339',
    projectId: 'mobilecmms-adbd6',
    authDomain: 'mobilecmms-adbd6.firebaseapp.com',
    storageBucket: 'mobilecmms-adbd6.appspot.com',
    measurementId: 'G-NWWF8NNTVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQra2T94w8j7rrxxo9e4kJDhR184IjyE',
    appId: '1:560383687339:android:a73fa24e2799bb6cd1d5ee',
    messagingSenderId: '560383687339',
    projectId: 'mobilecmms-adbd6',
    storageBucket: 'mobilecmms-adbd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzCSWoB0Rj_fYFQXAnAMEEvt2DM4yPmY',
    appId: '1:560383687339:ios:e688039e62f451e8d1d5ee',
    messagingSenderId: '560383687339',
    projectId: 'mobilecmms-adbd6',
    storageBucket: 'mobilecmms-adbd6.appspot.com',
    iosClientId: '560383687339-elj4ulg388iiig0evsejpmka649pfhlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakarCmms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzCSWoB0Rj_fYFQXAnAMEEvt2DM4yPmY',
    appId: '1:560383687339:ios:c34658b8c5b813ebd1d5ee',
    messagingSenderId: '560383687339',
    projectId: 'mobilecmms-adbd6',
    storageBucket: 'mobilecmms-adbd6.appspot.com',
    iosClientId: '560383687339-b48cpgtv858p62n2o83rtpvh2de5e91u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakarCmms.RunnerTests',
  );
}
